/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import model.PersonalProfile;

/**
 *
 * @author frida
 */
public class CreateJPanel extends javax.swing.JPanel {
    PersonalProfile personalProfile;

    /**
     * Creates new form CreateJPanel
     */
    public CreateJPanel(PersonalProfile p) {
        personalProfile=p;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTelNo = new javax.swing.JTextField();
        lbLasNa = new javax.swing.JLabel();
        lbFaxNo = new javax.swing.JLabel();
        txtLasNa = new javax.swing.JTextField();
        txtFaxNo = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        lbNatio = new javax.swing.JLabel();
        lbEmail = new javax.swing.JLabel();
        txtNatio = new javax.swing.JTextField();
        lbPhone = new javax.swing.JLabel();
        lbGender = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        txtDriLi = new javax.swing.JTextField();
        txtGender = new javax.swing.JTextField();
        lbEdu = new javax.swing.JLabel();
        lbDriLi = new javax.swing.JLabel();
        txtEdu = new javax.swing.JTextField();
        lbSSN = new javax.swing.JLabel();
        lbProf = new javax.swing.JLabel();
        txtSSN = new javax.swing.JTextField();
        txtProf = new javax.swing.JTextField();
        lbAdr1 = new javax.swing.JLabel();
        lbSkill = new javax.swing.JLabel();
        txtAds1 = new javax.swing.JTextField();
        txtSkill = new javax.swing.JTextField();
        lbAds2 = new javax.swing.JLabel();
        txtHob = new javax.swing.JTextField();
        txtAdr2 = new javax.swing.JTextField();
        lbHob = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        lbCity = new javax.swing.JLabel();
        txtState = new javax.swing.JTextField();
        lbFirNa = new javax.swing.JLabel();
        lbState = new javax.swing.JLabel();
        lbZip = new javax.swing.JLabel();
        lbTitle = new javax.swing.JLabel();
        txtFirNa = new javax.swing.JTextField();
        txtZip = new javax.swing.JTextField();
        lbTelNo = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();

        lbLasNa.setText("Last Name");

        lbFaxNo.setText("Fax Number");

        lbNatio.setText("Nationality");

        lbEmail.setText("Email");

        lbPhone.setText("Phone");

        lbGender.setText("Gender");

        lbEdu.setText("Education");

        lbDriLi.setText("Driver License");

        lbSSN.setText("State Social Security Number");

        lbProf.setText("Professional");

        lbAdr1.setText("Address Line 1");

        lbSkill.setText("Skills");

        lbAds2.setText("Address Line 2");

        lbHob.setText("Hobbies");

        lbCity.setText("City");

        lbFirNa.setText("First Name");

        lbState.setText("State");

        lbZip.setText("ZIP");

        lbTitle.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lbTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitle.setText("Create Personal Profile");

        lbTelNo.setText("Telephone Number");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 708, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbState)
                        .addGap(18, 18, 18)
                        .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbCity)
                        .addGap(18, 18, 18)
                        .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbAds2)
                        .addGap(18, 18, 18)
                        .addComponent(txtAdr2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbAdr1)
                        .addGap(18, 18, 18)
                        .addComponent(txtAds1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbSSN)
                        .addGap(18, 18, 18)
                        .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbDriLi)
                        .addGap(18, 18, 18)
                        .addComponent(txtDriLi, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbPhone)
                        .addGap(18, 18, 18)
                        .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbEmail)
                        .addGap(18, 18, 18)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lbLasNa)
                            .addGap(18, 18, 18)
                            .addComponent(txtLasNa, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lbFirNa)
                            .addGap(18, 18, 18)
                            .addComponent(txtFirNa, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbZip)
                        .addGap(18, 18, 18)
                        .addComponent(txtZip, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbTelNo)
                        .addGap(18, 18, 18)
                        .addComponent(txtTelNo, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbFaxNo)
                        .addGap(18, 18, 18)
                        .addComponent(txtFaxNo, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbNatio)
                        .addGap(18, 18, 18)
                        .addComponent(txtNatio, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbGender)
                        .addGap(18, 18, 18)
                        .addComponent(txtGender, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbEdu)
                        .addGap(18, 18, 18)
                        .addComponent(txtEdu, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbProf)
                        .addGap(18, 18, 18)
                        .addComponent(txtProf, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbSkill)
                        .addGap(18, 18, 18)
                        .addComponent(txtSkill, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbHob)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSave)
                            .addComponent(txtHob, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lbTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFirNa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbFirNa)
                    .addComponent(txtZip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbZip))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtLasNa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbLasNa)
                    .addComponent(txtTelNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTelNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbEmail)
                    .addComponent(txtFaxNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbFaxNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPhone)
                    .addComponent(txtNatio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNatio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDriLi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDriLi)
                    .addComponent(txtGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbGender))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbSSN)
                    .addComponent(txtEdu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbEdu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAds1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbAdr1)
                    .addComponent(txtProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbProf))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAdr2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbAds2)
                    .addComponent(txtSkill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbSkill))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCity)
                    .addComponent(txtHob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbHob))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbState))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(btnSave)
                .addGap(27, 27, 27))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String firNa=txtFirNa.getText();
        String lasNa=txtLasNa.getText();
        String adr1=txtAds1.getText();
        String adr2=txtAdr2.getText();
        String city=txtCity.getText();
        String driLi=txtDriLi.getText();
        String edu=txtEdu.getText();
        String email=txtEmail.getText();
        String faxNo=txtFaxNo.getText();
        String gender=txtGender.getText();
        String hob=txtHob.getText();
        String natio=txtNatio.getText();
        String phone=txtPhone.getText();
        String prof=txtProf.getText();
        String ssn=txtSSN.getText();
        String skill=txtSkill.getText();
        String state=txtState.getText();
        String telNo=txtTelNo.getText();
        String zip=txtZip.getText();
        
        personalProfile.setAddressLine1(adr1);
        personalProfile.setAddressLine2(adr2);
        personalProfile.setCity(city);
        personalProfile.setDriverLicense(driLi);
        personalProfile.setEducation(edu);
        personalProfile.setEmail(email);
        personalProfile.setFaxNumber(faxNo);
        personalProfile.setFirstName(firNa);
        personalProfile.setGender(gender);
        personalProfile.setHobbies(hob);
        personalProfile.setLastName(lasNa);
        personalProfile.setNationality(natio);
        personalProfile.setPhone(phone);
        personalProfile.setProfessional(prof);
        personalProfile.setSkills(skill);
        personalProfile.setState(state);
        personalProfile.setStateSocialSecurityNumber(state);
        personalProfile.setTelephoneNumber(phone);
        personalProfile.setZip(zip);
        
        JOptionPane.showMessageDialog(this, "Saved successfully!");
        
        txtFirNa.setText("");
        txtAdr2.setText("");
        txtAds1.setText("");
        txtCity.setText("");
        txtDriLi.setText("");
        txtEdu.setText("");
        txtEmail.setText("");
        txtFaxNo.setText("");
        txtGender.setText("");
        txtHob.setText("");
        txtLasNa.setText("");
        txtNatio.setText("");
        txtPhone.setText("");
        txtProf.setText("");
        txtSSN.setText("");
        txtSkill.setText("");
        txtState.setText("");
        txtTelNo.setText("");
        txtZip.setText("");
        
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel lbAdr1;
    private javax.swing.JLabel lbAds2;
    private javax.swing.JLabel lbCity;
    private javax.swing.JLabel lbDriLi;
    private javax.swing.JLabel lbEdu;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbFaxNo;
    private javax.swing.JLabel lbFirNa;
    private javax.swing.JLabel lbGender;
    private javax.swing.JLabel lbHob;
    private javax.swing.JLabel lbLasNa;
    private javax.swing.JLabel lbNatio;
    private javax.swing.JLabel lbPhone;
    private javax.swing.JLabel lbProf;
    private javax.swing.JLabel lbSSN;
    private javax.swing.JLabel lbSkill;
    private javax.swing.JLabel lbState;
    private javax.swing.JLabel lbTelNo;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JLabel lbZip;
    private javax.swing.JTextField txtAdr2;
    private javax.swing.JTextField txtAds1;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtDriLi;
    private javax.swing.JTextField txtEdu;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFaxNo;
    private javax.swing.JTextField txtFirNa;
    private javax.swing.JTextField txtGender;
    private javax.swing.JTextField txtHob;
    private javax.swing.JTextField txtLasNa;
    private javax.swing.JTextField txtNatio;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtProf;
    private javax.swing.JTextField txtSSN;
    private javax.swing.JTextField txtSkill;
    private javax.swing.JTextField txtState;
    private javax.swing.JTextField txtTelNo;
    private javax.swing.JTextField txtZip;
    // End of variables declaration//GEN-END:variables
}
