
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Dimension;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author frida
 */
public class MainJFrame extends javax.swing.JFrame {
    

private PersonDirectory personDirectory = new PersonDirectory();
    

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        addSampleData();
        WorkArea.setLayout(new CardLayout());
        WorkArea.add(addPanel, "addPanel");
        WorkArea.add(searchPanel, "searchPanel");
        WorkArea.add(listPanel, "listPanel");
        WorkArea.add(deletePanel, "deletePanel");
        
    }
    private JTable personTable;

    private void addSampleData() {
    personDirectory.addPerson(new Person("Alice", "Johnson", "123-45-6789", 30,
            new Address("123 Elm St", "101", "Los Angeles", "CA", "90001", "555-1234"),
            new Address("456 Maple Ave", "201", "Los Angeles", "CA", "90002", "555-5678")));

    personDirectory.addPerson(new Person("Bob", "Smith", "234-56-7890", 40,
            new Address("789 Pine St", "202", "San Francisco", "CA", "94107", "555-8765"),
            new Address("987 Oak St", "303", "San Francisco", "CA", "94108", "555-4321")));

    personDirectory.addPerson(new Person("Charlie", "Brown", "345-67-8901", 28,
            new Address("321 Cedar St", "1A", "San Jose", "CA", "95112", "555-6789"),
            new Address("654 Birch Blvd", "401", "San Jose", "CA", "95113", "555-9876")));

    personDirectory.addPerson(new Person("Diana", "Prince", "456-78-9012", 35,
            new Address("111 Cypress Ave", "102", "Sacramento", "CA", "95814", "555-2468"),
            new Address("999 Redwood Rd", "502", "Sacramento", "CA", "95815", "555-7531")));

    personDirectory.addPerson(new Person("Emily", "Davis", "567-89-0123", 25,
            new Address("222 Spruce Dr", "3B", "San Diego", "CA", "92101", "555-1357"),
            new Address("888 Palm St", "604", "San Diego", "CA", "92102", "555-9753")));
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        ContralPanel = new javax.swing.JPanel();
        addbtn = new javax.swing.JButton();
        listbtn = new javax.swing.JButton();
        searchPersonbtn = new javax.swing.JButton();
        titlelbl = new javax.swing.JLabel();
        deletebtn = new javax.swing.JButton();
        WorkArea = new javax.swing.JPanel();
        searchPanel = new javax.swing.JPanel();
        titleLabel1 = new javax.swing.JLabel();
        searchTxt = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        listPanel = new javax.swing.JPanel();
        addPanel = new javax.swing.JPanel();
        firNaTextField = new javax.swing.JTextField();
        lasNalbl = new javax.swing.JLabel();
        firNalbl = new javax.swing.JLabel();
        lasNaTextField = new javax.swing.JTextField();
        ssnlbl = new javax.swing.JLabel();
        ssnTextField = new javax.swing.JTextField();
        agelbl = new javax.swing.JLabel();
        ageTextField = new javax.swing.JTextField();
        homeAddPanel = new javax.swing.JPanel();
        homeStrtxt = new javax.swing.JTextField();
        unitNoLabel = new javax.swing.JLabel();
        homeUnitNotxt = new javax.swing.JTextField();
        cityLabel = new javax.swing.JLabel();
        homeCitytxt = new javax.swing.JTextField();
        stateLabel = new javax.swing.JLabel();
        homeStatetxt = new javax.swing.JTextField();
        zipLabel = new javax.swing.JLabel();
        homeziptxt = new javax.swing.JTextField();
        phoLabel = new javax.swing.JLabel();
        homePhoTxt = new javax.swing.JTextField();
        strAddLabel = new javax.swing.JLabel();
        homeAddlbl = new javax.swing.JLabel();
        workAddLabel = new javax.swing.JLabel();
        workCityTxt = new javax.swing.JTextField();
        workZipTxt = new javax.swing.JTextField();
        unitNoLabel1 = new javax.swing.JLabel();
        phoLabel1 = new javax.swing.JLabel();
        workStateTxt = new javax.swing.JTextField();
        zipLabel1 = new javax.swing.JLabel();
        workPhoTxt = new javax.swing.JTextField();
        strAddLabel1 = new javax.swing.JLabel();
        workStrAddTxt = new javax.swing.JTextField();
        workUnitNoTxt = new javax.swing.JTextField();
        stateLabel1 = new javax.swing.JLabel();
        cityLabel1 = new javax.swing.JLabel();
        createButton = new javax.swing.JButton();
        updatebtn = new javax.swing.JButton();
        deletePanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ContralPanel.setBorder(new javax.swing.border.MatteBorder(null));
        ContralPanel.setAutoscrolls(true);

        addbtn.setText("Add Person");
        addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtnActionPerformed(evt);
            }
        });

        listbtn.setText("List Person");
        listbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listbtnActionPerformed(evt);
            }
        });

        searchPersonbtn.setText("Search");
        searchPersonbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchPersonbtnActionPerformed(evt);
            }
        });

        titlelbl.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        titlelbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titlelbl.setText("Person Profile");

        deletebtn.setText("Delete");
        deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ContralPanelLayout = new javax.swing.GroupLayout(ContralPanel);
        ContralPanel.setLayout(ContralPanelLayout);
        ContralPanelLayout.setHorizontalGroup(
            ContralPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titlelbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(ContralPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(ContralPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(addbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(listbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(searchPersonbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deletebtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ContralPanelLayout.setVerticalGroup(
            ContralPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContralPanelLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(titlelbl)
                .addGap(61, 61, 61)
                .addComponent(addbtn)
                .addGap(30, 30, 30)
                .addComponent(listbtn)
                .addGap(26, 26, 26)
                .addComponent(searchPersonbtn)
                .addGap(18, 18, 18)
                .addComponent(deletebtn)
                .addContainerGap(136, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(ContralPanel);

        WorkArea.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        WorkArea.setAutoscrolls(true);
        WorkArea.setLayout(new java.awt.CardLayout());

        titleLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        titleLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel1.setText("Search for Person");

        searchTxt.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout searchPanelLayout = new javax.swing.GroupLayout(searchPanel);
        searchPanel.setLayout(searchPanelLayout);
        searchPanelLayout.setHorizontalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addComponent(titleLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 27, Short.MAX_VALUE))
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(searchTxt)
                .addGap(18, 18, 18)
                .addComponent(searchButton)
                .addGap(77, 77, 77))
        );
        searchPanelLayout.setVerticalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(titleLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(136, 136, 136)
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(207, Short.MAX_VALUE))
        );

        WorkArea.add(searchPanel, "card4");

        javax.swing.GroupLayout listPanelLayout = new javax.swing.GroupLayout(listPanel);
        listPanel.setLayout(listPanelLayout);
        listPanelLayout.setHorizontalGroup(
            listPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 626, Short.MAX_VALUE)
        );
        listPanelLayout.setVerticalGroup(
            listPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 458, Short.MAX_VALUE)
        );

        WorkArea.add(listPanel, "card3");

        addPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lasNalbl.setText("Last Name");

        firNalbl.setText("First Name");

        ssnlbl.setText("Social Security Number");

        agelbl.setText("Age");

        homeStrtxt.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        homeStrtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeStrtxtActionPerformed(evt);
            }
        });

        unitNoLabel.setText("Unit Number");

        homeUnitNotxt.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        cityLabel.setText("City");

        homeCitytxt.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        stateLabel.setText("State");

        homeStatetxt.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        zipLabel.setText("Zip Code");

        homeziptxt.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        phoLabel.setText("Phone Number");

        homePhoTxt.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        strAddLabel.setText("Street Address");

        homeAddlbl.setText("Home Address");

        javax.swing.GroupLayout homeAddPanelLayout = new javax.swing.GroupLayout(homeAddPanel);
        homeAddPanel.setLayout(homeAddPanelLayout);
        homeAddPanelLayout.setHorizontalGroup(
            homeAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeAddPanelLayout.createSequentialGroup()
                .addGroup(homeAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(homeAddPanelLayout.createSequentialGroup()
                        .addGroup(homeAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(homeAddPanelLayout.createSequentialGroup()
                                .addComponent(unitNoLabel)
                                .addGap(24, 24, 24)
                                .addComponent(homeUnitNotxt))
                            .addGroup(homeAddPanelLayout.createSequentialGroup()
                                .addComponent(strAddLabel)
                                .addGap(10, 10, 10)
                                .addComponent(homeStrtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(homeAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cityLabel)
                            .addComponent(stateLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(homeAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(homeStatetxt, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                            .addComponent(homeCitytxt))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(homeAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(zipLabel)
                            .addComponent(phoLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(homeAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(homeziptxt, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                            .addComponent(homePhoTxt)))
                    .addComponent(homeAddlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        homeAddPanelLayout.setVerticalGroup(
            homeAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeAddPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(homeAddlbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(homeAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(homeStrtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(homeCitytxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(homeziptxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(homeAddPanelLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(homeAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(strAddLabel)
                            .addComponent(cityLabel)
                            .addComponent(zipLabel))))
                .addGap(10, 10, 10)
                .addGroup(homeAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(homeAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(homeUnitNotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(unitNoLabel))
                    .addComponent(homeStatetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(homePhoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(homeAddPanelLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(homeAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(stateLabel)
                            .addComponent(phoLabel)))))
        );

        workAddLabel.setText("Work Address");

        workCityTxt.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        workZipTxt.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        unitNoLabel1.setText("Unit Number");

        phoLabel1.setText("Phone Number");

        workStateTxt.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        zipLabel1.setText("Zip Code");

        workPhoTxt.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        strAddLabel1.setText("Street Address");

        workStrAddTxt.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        workUnitNoTxt.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        stateLabel1.setText("State");

        cityLabel1.setText("City");

        createButton.setText("Create");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });

        updatebtn.setText("Update");
        updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addPanelLayout = new javax.swing.GroupLayout(addPanel);
        addPanel.setLayout(addPanelLayout);
        addPanelLayout.setHorizontalGroup(
            addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ssnlbl)
                    .addComponent(firNalbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(firNaTextField)
                    .addComponent(ssnTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE))
                .addGap(62, 62, 62)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(addPanelLayout.createSequentialGroup()
                        .addComponent(lasNalbl)
                        .addGap(18, 18, 18)
                        .addComponent(lasNaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addPanelLayout.createSequentialGroup()
                        .addComponent(agelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(305, 305, 305))
            .addGroup(addPanelLayout.createSequentialGroup()
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addPanelLayout.createSequentialGroup()
                        .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addPanelLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(workAddLabel)
                                    .addComponent(strAddLabel1)))
                            .addGroup(addPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(unitNoLabel1)))
                        .addGap(10, 10, 10)
                        .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(addPanelLayout.createSequentialGroup()
                                .addComponent(workStrAddTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(cityLabel1)
                                .addGap(25, 25, 25))
                            .addGroup(addPanelLayout.createSequentialGroup()
                                .addComponent(workUnitNoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(stateLabel1)
                                .addGap(18, 18, 18)))
                        .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(workStateTxt)
                            .addComponent(workCityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(addPanelLayout.createSequentialGroup()
                                .addComponent(phoLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(workPhoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(addPanelLayout.createSequentialGroup()
                                .addComponent(zipLabel1)
                                .addGap(34, 34, 34)
                                .addComponent(workZipTxt))))
                    .addGroup(addPanelLayout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(createButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(updatebtn, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(addPanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(homeAddPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(202, Short.MAX_VALUE))
        );
        addPanelLayout.setVerticalGroup(
            addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPanelLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(firNaTextField)
                        .addComponent(lasNalbl)
                        .addComponent(lasNaTextField))
                    .addComponent(firNalbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ssnTextField)
                        .addComponent(agelbl)
                        .addComponent(ageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ssnlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(homeAddPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(workAddLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(workStrAddTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(addPanelLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addPanelLayout.createSequentialGroup()
                                .addComponent(strAddLabel1)
                                .addGap(18, 18, 18)
                                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(unitNoLabel1)
                                    .addComponent(workUnitNoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(stateLabel1)))
                            .addComponent(cityLabel1)
                            .addGroup(addPanelLayout.createSequentialGroup()
                                .addComponent(workCityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(workStateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(addPanelLayout.createSequentialGroup()
                                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(zipLabel1)
                                    .addComponent(workZipTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)
                                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(phoLabel1)
                                    .addComponent(workPhoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(18, 18, 18)
                .addComponent(createButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(updatebtn)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        WorkArea.add(addPanel, "card2");

        javax.swing.GroupLayout deletePanelLayout = new javax.swing.GroupLayout(deletePanel);
        deletePanel.setLayout(deletePanelLayout);
        deletePanelLayout.setHorizontalGroup(
            deletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 643, Short.MAX_VALUE)
        );
        deletePanelLayout.setVerticalGroup(
            deletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 458, Short.MAX_VALUE)
        );

        WorkArea.add(deletePanel, "card5");

        jSplitPane1.setRightComponent(WorkArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 789, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtnActionPerformed
        // TODO add your handling code here:
        System.out.println("Add Person button clicked");
        CardLayout cardLayout = (CardLayout) WorkArea.getLayout();
        cardLayout.show(WorkArea, "addPanel"); 
        

    }//GEN-LAST:event_addbtnActionPerformed

    private void listbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listbtnActionPerformed
                                              
        // Print to console for debugging purposes
        System.out.println("List Person button clicked");

        // Show the list panel using CardLayout
        CardLayout cardLayout = (CardLayout) WorkArea.getLayout();
        cardLayout.show(WorkArea, "listPanel"); 

        // Ensure listPanel has a layout that allows components to fill the space
        listPanel.setLayout(new BorderLayout());

        // Create a new JTable and wrap it in a JScrollPane
        personTable = new JTable();
        JScrollPane scrollPane = new JScrollPane(personTable);
        scrollPane.setPreferredSize(new Dimension(500, 300)); 

        // Clear any existing components and add the new scroll pane
        listPanel.removeAll();
        listPanel.add(scrollPane, BorderLayout.CENTER);

        // Ensure the panel is refreshed
        listPanel.revalidate();
        listPanel.repaint();

        // Define the columns for the JTable
        String[] columnNames = {"First Name", "Last Name", "SSN", "Age", "Home Address", "Work Address"};

        // Get the list of persons from the person directory
        List<Person> persons = personDirectory.listPersons();

        // Create a table model and set it for the JTable
        DefaultTableModel tableModel = new DefaultTableModel(columnNames, 0);
        personTable.setModel(tableModel);

        // Populate the table model with the data
        for (Person person : persons) {
            String homeAddress = person.getHomeAddress().toString(); 
            String workAddress = person.getWorkAddress().toString(); 
            Object[] rowData = {
                person.getFirstName(),
                person.getLastName(),
                person.getSocialSecurityNumber(),
                person.getAge(),
                homeAddress,
                workAddress
            };
            tableModel.addRow(rowData);
        }
      
    }//GEN-LAST:event_listbtnActionPerformed

    private void searchPersonbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchPersonbtnActionPerformed
        // TODO add your handling code here:
        System.out.println("Search Person button clicked");
        CardLayout cardLayout = (CardLayout) WorkArea.getLayout();
        cardLayout.show(WorkArea, "searchPanel"); 
        
    }//GEN-LAST:event_searchPersonbtnActionPerformed

    private void deletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtnActionPerformed
        // TODO add your handling code here:
        CardLayout cardLayout = (CardLayout) WorkArea.getLayout();
        cardLayout.show(WorkArea, "deletePanel"); 
        
        
        
    }//GEN-LAST:event_deletebtnActionPerformed

    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnActionPerformed
        // TODO add your handling code here:
        String firstName = firNaTextField.getText().trim();
        String lastName = lasNaTextField.getText().trim();
        String ssn = ssnTextField.getText().trim();
        String ageText = ageTextField.getText().trim();
        String homeStreet = homeStrtxt.getText().trim();
        String homeUnit = homeUnitNotxt.getText().trim();
        String homeCity = homeCitytxt.getText().trim();
        String homeState = homeStatetxt.getText().trim();
        String homeZip = homeziptxt.getText().trim();
        String homePhone = homePhoTxt.getText().trim();
        String workStreet = workStrAddTxt.getText().trim();
        String workUnit = workUnitNoTxt.getText().trim();
        String workCity = workCityTxt.getText().trim();
        String workState = workStateTxt.getText().trim();
        String workZip = workZipTxt.getText().trim();
        String workPhone = workPhoTxt.getText().trim();

    
    if (firstName.isEmpty() || lastName.isEmpty() || ssn.isEmpty() || ageText.isEmpty() ||
        homeStreet.isEmpty() || homeCity.isEmpty() || homeState.isEmpty() || homeZip.isEmpty() ||
        homePhone.isEmpty() || workStreet.isEmpty() || workCity.isEmpty() || 
        workState.isEmpty() || workZip.isEmpty() || workPhone.isEmpty()) {
        
        JOptionPane.showMessageDialog(this, "All fields are required. Please fill out every field." );
                                     
        return; 
    }

    
    int age;
    try {
        age = Integer.parseInt(ageText);
        if (age <= 0) {
            JOptionPane.showMessageDialog(this, "Age must be a positive number.");
            return; 
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Please enter a valid number for age.");
        return; 
    }

    
    Address homeAddress = new Address(homeStreet, homeUnit, homeCity, homeState, homeZip, homePhone);
    Address workAddress = new Address(workStreet, workUnit, workCity, workState, workZip, workPhone);
    Person newPerson = new Person(firstName, lastName, ssn, age, homeAddress, workAddress);
    
    personDirectory.addPerson(newPerson);
    JOptionPane.showMessageDialog(this, "Person updated successfully!");
    }//GEN-LAST:event_updatebtnActionPerformed

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        // TODO add your handling code here:
    String firstName = firNaTextField.getText().trim();
    String lastName = lasNaTextField.getText().trim();
    String ssn = ssnTextField.getText().trim();
    String ageText = ageTextField.getText().trim();
    String homeStreet = homeStrtxt.getText().trim();
    String homeUnit = homeUnitNotxt.getText().trim();
    String homeCity = homeCitytxt.getText().trim();
    String homeState = homeStatetxt.getText().trim();
    String homeZip = homeziptxt.getText().trim();
    String homePhone = homePhoTxt.getText().trim();
    String workStreet = workStrAddTxt.getText().trim();
    String workUnit = workUnitNoTxt.getText().trim();
    String workCity = workCityTxt.getText().trim();
    String workState = workStateTxt.getText().trim();
    String workZip = workZipTxt.getText().trim();
    String workPhone = workPhoTxt.getText().trim();

    
    if (firstName.isEmpty() || lastName.isEmpty() || ssn.isEmpty() || ageText.isEmpty() ||
        homeStreet.isEmpty() || homeCity.isEmpty() || homeState.isEmpty() || homeZip.isEmpty() ||
        homePhone.isEmpty() || workStreet.isEmpty() || workCity.isEmpty() || 
        workState.isEmpty() || workZip.isEmpty() || workPhone.isEmpty()) {
        
        JOptionPane.showMessageDialog(this, "All fields are required. Please fill out every field." );
                                     
        return; 
    }

    
    int age;
    try {
        age = Integer.parseInt(ageText);
        if (age <= 0) {
            JOptionPane.showMessageDialog(this, "Age must be a positive number.");
            return; 
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Please enter a valid number for age.");
        return; 
    }

    
    Address homeAddress = new Address(homeStreet, homeUnit, homeCity, homeState, homeZip, homePhone);
    Address workAddress = new Address(workStreet, workUnit, workCity, workState, workZip, workPhone);
    Person newPerson = new Person(firstName, lastName, ssn, age, homeAddress, workAddress);
    
    personDirectory.addPerson(newPerson);
    JOptionPane.showMessageDialog(this, "Person added successfully!");

    }//GEN-LAST:event_createButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
  
        // TODO add your handling code here:
        String criteria = searchTxt.getText();
        Person foundPerson = personDirectory.searchPerson(criteria);

        if (foundPerson!= null) {
            System.out.println("Found person");

        
        firNaTextField.setText(foundPerson.getFirstName());
        lasNaTextField.setText(foundPerson.getLastName());
        ssnTextField.setText(foundPerson.getSocialSecurityNumber());
        ageTextField.setText(String.valueOf(foundPerson.getAge()));

        
        homeStrtxt.setText(foundPerson.getHomeAddress().getStreetAddress());
        homeUnitNotxt.setText(foundPerson.getHomeAddress().getUnitNumber());
        homeCitytxt.setText(foundPerson.getHomeAddress().getCity());
        homeStatetxt.setText(foundPerson.getHomeAddress().getState());
        homeziptxt.setText(foundPerson.getHomeAddress().getZipCode());
        homePhoTxt.setText(foundPerson.getHomeAddress().getPhoneNumber());

        
        workStrAddTxt.setText(foundPerson.getWorkAddress().getStreetAddress());
        workUnitNoTxt.setText(foundPerson.getWorkAddress().getUnitNumber());
        workCityTxt.setText(foundPerson.getWorkAddress().getCity());
        workStateTxt.setText(foundPerson.getWorkAddress().getState());
        workZipTxt.setText(foundPerson.getWorkAddress().getZipCode());
        workPhoTxt.setText(foundPerson.getWorkAddress().getPhoneNumber());

        
        CardLayout cardLayout = (CardLayout) WorkArea.getLayout();
        cardLayout.show(WorkArea, "addPanel");
        } else {
            JOptionPane.showMessageDialog(this, "No person found!");
        }

    }//GEN-LAST:event_searchButtonActionPerformed

    private void homeStrtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeStrtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_homeStrtxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ContralPanel;
    private javax.swing.JPanel WorkArea;
    private javax.swing.JPanel addPanel;
    private javax.swing.JButton addbtn;
    private javax.swing.JTextField ageTextField;
    private javax.swing.JLabel agelbl;
    private javax.swing.JLabel cityLabel;
    private javax.swing.JLabel cityLabel1;
    private javax.swing.JButton createButton;
    private javax.swing.JPanel deletePanel;
    private javax.swing.JButton deletebtn;
    private javax.swing.JTextField firNaTextField;
    private javax.swing.JLabel firNalbl;
    private javax.swing.JPanel homeAddPanel;
    private javax.swing.JLabel homeAddlbl;
    private javax.swing.JTextField homeCitytxt;
    private javax.swing.JTextField homePhoTxt;
    private javax.swing.JTextField homeStatetxt;
    private javax.swing.JTextField homeStrtxt;
    private javax.swing.JTextField homeUnitNotxt;
    private javax.swing.JTextField homeziptxt;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextField lasNaTextField;
    private javax.swing.JLabel lasNalbl;
    private javax.swing.JPanel listPanel;
    private javax.swing.JButton listbtn;
    private javax.swing.JLabel phoLabel;
    private javax.swing.JLabel phoLabel1;
    private javax.swing.JButton searchButton;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JButton searchPersonbtn;
    private javax.swing.JTextField searchTxt;
    private javax.swing.JTextField ssnTextField;
    private javax.swing.JLabel ssnlbl;
    private javax.swing.JLabel stateLabel;
    private javax.swing.JLabel stateLabel1;
    private javax.swing.JLabel strAddLabel;
    private javax.swing.JLabel strAddLabel1;
    private javax.swing.JLabel titleLabel1;
    private javax.swing.JLabel titlelbl;
    private javax.swing.JLabel unitNoLabel;
    private javax.swing.JLabel unitNoLabel1;
    private javax.swing.JButton updatebtn;
    private javax.swing.JLabel workAddLabel;
    private javax.swing.JTextField workCityTxt;
    private javax.swing.JTextField workPhoTxt;
    private javax.swing.JTextField workStateTxt;
    private javax.swing.JTextField workStrAddTxt;
    private javax.swing.JTextField workUnitNoTxt;
    private javax.swing.JTextField workZipTxt;
    private javax.swing.JLabel zipLabel;
    private javax.swing.JLabel zipLabel1;
    // End of variables declaration//GEN-END:variables
}
