/*
 * This file is generated by jOOQ.
 */
package com.example.jooq;


import com.example.jooq.tables.SearchResults;
import com.example.jooq.tables.records.SearchResultsRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<SearchResultsRecord> SEARCH_RESULTS_PKEY = Internal.createUniqueKey(SearchResults.SEARCH_RESULTS, DSL.name("search_results_pkey"), new TableField[] { SearchResults.SEARCH_RESULTS.ID }, true);
}
