/*
 * This file is generated by jOOQ.
 */
package com.example.jooq;


import com.example.jooq.tables.SearchResults;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.search_results</code>.
     */
    public static final SearchResults SEARCH_RESULTS = SearchResults.SEARCH_RESULTS;
}
